language: node_js
node_js:
  - '10'

cache:
  directories:
    - node_modules
notifications:
  email: false
node_js: '10'
git:
  depth: 1

stages:
  - 'Test'
  - name: 'Deploy'
    if: branch = master AND type = push

jobs:
  include:
    - stage: 'Test'
    - stage: 'Deploy'
      script: yarn semantic-release
